### ISSUE TITLE
Cache problem with Node.js

### ISSUE THREAD

**Issue by KOliver94** [pre-commit/action#45]
Hi everybody,

I noticed a problem with pre-commit action's cache and using Node.js environment. I'm using eslint in pre-commit and to make eslint-plugin-import work properly I need to install the dependencies. So, my workflow looks the following:
```
jobs:
  pre-commit:
    name: Pre-commit hooks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Use Node.js 14
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - name: Install frontend dependencies
      run: npm install
      working-directory: frontend
    - name: Run pre-commit hooks
      uses: pre-commit/action@v2.0.0
```

The problem is that because I only use `node-version: '14'` in the setup-node phase the Node.js version will change after a while to a newer version but the pre-commit action's cache does not care for that and tries to use a cached version where a previous version of Node.js was used and the following error occurs:
```
eslint...................................................................Failed
- hook id: eslint
- exit code: 127

/home/runner/.cache/pre-commit/repoibq27hfw/node_env-system/bin/node: line 5: /opt/hostedtoolcache/node/14.8.0/x64/bin/node: No such file or directory
/home/runner/.cache/pre-commit/repoibq27hfw/node_env-system/bin/node: line 5: /opt/hostedtoolcache/node/14.8.0/x64/bin/node: No such file or directory

##[error]The process '/opt/hostedtoolcache/Python/3.8.5/x64/bin/pre-commit' failed with exit code 1
```
and I can see that the setup-node used version 14.9.0.
```
Run actions/setup-node@v2-beta
version: 14
Found in cache @ /opt/hostedtoolcache/node/14.9.0/x64
```

I used a "workaround" a specified a fully qualified node-version but I don't think this is the best solution. Is there any way to either disable the cache or make it sensitive for the Node.js version?

Thanks!

**Comment by asottile** [comment]
here's what we do for python: https://github.com/pre-commit/action/blob/ef992f5a2309f333dac57d17536f48de79413225/index.js#L52-L53

**Comment by FrancoisFerrariKpler** [comment]
Hi,
I have the same problem but using graphQL, and as I'm new to both typescript and graphQL, I have not yet been able to figure out what to do exactly to solve this problem.

I have tried to add a ```uses: actions/cache@v2``` line in my .yml file but then some parameters where missing like keys and path for the cache action and I'm not sure what to specify in this parameters

Would you have some hints to help me ?

**Below is my .github/workflows/pre-commit.yml file:**
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - uses: pre-commit/action@v2.0.0

**And it fails with:**
/opt/hostedtoolcache/Python/3.8.5/x64/bin/pre-commit run --show-diff-on-failure --color=always --all-files
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
Don't commit to branch...................................................Passed
CRLF end-lines checker...................................................Passed
CRLF end-lines remover...................................................Passed
Check hooks apply to the repository......................................Passed
Check for useless excludes...............................................Passed
Prettier.................................................................Failed
- hook id: prettier
- exit code: 127

/home/runner/.cache/pre-commit/repon7pcj2u6/node_env-system/bin/node: line 5: /opt/hostedtoolcache/node/12.18.3/x64/bin/node: No such file or directory
/home/runner/.cache/pre-commit/repon7pcj2u6/node_env-system/bin/node: line 5: /opt/hostedtoolcache/node/12.18.3/x64/bin/node: No such file or directory

ESLint...................................................................Passed
Error: The process '/opt/hostedtoolcache/Python/3.8.5/x64/bin/pre-commit' failed with exit code 1

**Comment by asottile** [comment]
this should be fixed already in the latest version of pre-commit, what version are you running?

**Comment by ineiti** [comment]
Running `pre-commit/action@2.0.0` using a matrix here, and it still fails...

**Comment by asottile** [comment]
then I'd recommend you try out https://pre-commit.ci instead -- it has better features anyway and github's stuff is probably un-repairably broken

you also haven't shown any output so I can't know whether this is the same issue or not
